### ISSUE TITLE
Empty tractograms get archived anyway

### ISSUE THREAD

**Issue by giulia-berto** [brainlife/validator-neuro-track#14]
Empty tractograms pass the validator only with a warning and get archived anyway. Is this what we want? I think that the validator should fail.

**Comment by bacaron** [comment]
We changed this because some situations will result in empty tracts (i.e. roi 2 roi tracking), or tracking multiple tracts at the same time, and we didn't want it to outright fail completely.

I don't know of a good solution for this.

**Comment by giulia-berto** [comment]
ah ok, I see. I changed the app code I was working on so that it's failing there (instead of failing in the validator).
