### ISSUE TITLE
Detect .tck v.s. .trk fileformat

### ISSUE THREAD

**Issue by soichih** [brainlife/validator-neuro-track#3]
If I feed a .tck file as .trk, the validator just reports this

![image](https://user-images.githubusercontent.com/923896/87562005-6ece7780-c68b-11ea-8379-52f786708db0.png)

It would be nice if the validator could report an error message like "we are expecting .trk but it looks like you've uploaded .tck file".

**Comment by soichih** [comment]
@guaje

**Comment by guaje** [comment]
Isn't this closed by #4?

**Comment by soichih** [comment]
Yes! Thanks!
