### ISSUE TITLE
fiber length histogram plot doesn't show up

### ISSUE THREAD

**Issue by giulia-berto** [brainlife/validator-neuro-track#9]
fiber length histogram plot doesn't show up (at least, not always). Maybe it is related to the latest code change, I can troubleshoot. @giulia-berto

**Comment by soichih** [comment]
![image](https://user-images.githubusercontent.com/923896/149542205-753b11a6-a133-47b2-ad64-7a9395284137.png)

**Comment by soichih** [comment]
@bhatiadheeraj Will you be able to troubleshoot this?

**Comment by giulia-berto** [comment]
solved.
